---
version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Dragonatorul"
    assignees:
      - "Dragonatorul"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      production-dependencies:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "httpx*"
          - "pyjwt*"
          - "cryptography*"
          - "fastmcp*"
      development-dependencies:
        patterns:
          - "pytest*"
          - "black*"
          - "flake8*"
          - "mypy*"
          - "isort*"
          - "bandit*"
          - "pre-commit*"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Dragonatorul"
    assignees:
      - "Dragonatorul"
    commit-message:
      prefix: "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Dragonatorul"
    assignees:
      - "Dragonatorul"
    commit-message:
      prefix: "ci"