blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Ideas & Concepts
    url: https://github.com/Dragonatorul/FalkorDB-FastMCP-Proxy/discussions/categories/ideas
    about: Share ideas for new features or discuss concept proposals
  - name: 🙋 Questions & Help
    url: https://github.com/Dragonatorul/FalkorDB-FastMCP-Proxy/discussions/categories/q-a
    about: Ask questions about usage, setup, or troubleshooting
  - name: 💬 General Discussion
    url: https://github.com/Dragonatorul/FalkorDB-FastMCP-Proxy/discussions/categories/general
    about: Chat about the project, share experiences, or discuss documentation
  - name: 🙌 Show and Tell
    url: https://github.com/Dragonatorul/FalkorDB-FastMCP-Proxy/discussions/categories/show-and-tell
    about: Show off your implementations, integrations, or cool use cases